import React, { useState } from 'react';
import './FAQ.scss';

const FAQ = () => {
    const [activeCategory, setActiveCategory] = useState('general');
    const [openQuestions, setOpenQuestions] = useState({});
    const [searchTerm, setSearchTerm] = useState('');

    const categories = [
        { id: 'general', name: 'General', icon: '❓' },
        { id: 'compliance', name: 'Compliance & Regulations', icon: '📋' },
        { id: 'technical', name: 'Technical', icon: '⚙️' },
        { id: 'pricing', name: 'Pricing & Plans', icon: '💰' },
        { id: 'account', name: 'Account & Data', icon: '👤' }
    ];

    const faqData = {
        general: [
            {
                question: "What is nutrition facts calculation and why do I need it?",
                answer: "Nutrition facts calculation determines the nutritional content of your food products based on ingredients and quantities. It's required by law for most packaged foods and helps consumers make informed decisions. Our platform automates this complex process that traditionally requires expensive lab testing."
            },
            {
                question: "How accurate are your nutrition calculations?",
                answer: "Our calculations achieve 99.9% accuracy using USDA and FDA databases combined with advanced algorithms that account for cooking losses, ingredient interactions, and processing effects. While we can't replace laboratory analysis for certain specialized claims, our calculations meet regulatory standards for standard nutrition labeling."
            },
            {
                question: "Can I use this for any type of food product?",
                answer: "Yes, our platform works for virtually all food products including baked goods, beverages, snacks, frozen foods, supplements, and restaurant items. We have ingredient data for raw materials, processed foods, and specialty ingredients. If an ingredient isn't in our database, you can add custom nutritional profiles."
            },
            {
                question: "How long does it take to generate a nutrition label?",
                answer: "Once you input your recipe, nutrition labels are generated instantly. The initial setup (entering ingredients and quantities) typically takes 5-15 minutes depending on recipe complexity. Compared to traditional lab testing which takes 2-3 weeks, this represents significant time savings."
            },
            {
                question: "Do you provide customer support?",
                answer: "Yes, we offer email support for all plans, phone support for Professional and Enterprise plans, and dedicated account managers for Enterprise customers. Our team includes nutrition labeling experts who can help with compliance questions and complex formulations."
            }
        ],
        compliance: [
            {
                question: "Are your nutrition labels FDA compliant?",
                answer: "Yes, all nutrition labels generated by our platform meet current FDA regulations including the updated Nutrition Facts label format. We follow FDA rounding rules, serving size guidelines, and Daily Value calculations. However, you're responsible for ensuring your specific product meets all applicable regulations."
            },
            {
                question: "Can I use calculated nutrition facts instead of lab testing?",
                answer: "For most standard nutrition labeling, yes. FDA allows nutrition facts to be calculated using appropriate databases and calculation methods. However, lab testing may be required for specific nutrient claims, organic certification, or certain specialized products. We recommend consulting with regulatory experts for complex cases."
            },
            {
                question: "What about allergen labeling requirements?",
                answer: "Our platform automatically identifies all 14 major allergens in your ingredients and generates appropriate allergen statements. We track allergens at the ingredient level and provide warnings for potential cross-contamination. However, you must verify allergen information with your suppliers and assess facility-level risks."
            },
            {
                question: "Do you handle international labeling requirements?",
                answer: "Currently, we focus on FDA (US) and basic international formats. For specific country requirements like Health Canada, EU regulations, or other international standards, we recommend consulting with local regulatory experts. Our Enterprise plan can include custom label formats for international markets."
            },
            {
                question: "What if my nutrition facts are audited?",
                answer: "Our calculations are based on recognized databases and methods accepted by regulatory agencies. We provide detailed calculation reports and source documentation that you can present during audits. However, regulatory compliance is ultimately your responsibility as the food manufacturer."
            }
        ],
        technical: [
            {
                question: "How do I input recipes with complex preparations?",
                answer: "Our platform handles multi-step recipes, cooking losses, yield calculations, and ingredient substitutions. You can account for water loss during baking, fat absorption during frying, and other processing effects. For very complex products, our Professional services team can help optimize your recipe setup."
            },
            {
                question: "Can I integrate this with my existing systems?",
                answer: "Yes, our Professional and Enterprise plans include API access for integration with ERP systems, inventory management, and other business tools. We also offer data export in multiple formats including Excel, CSV, and PDF for easy integration with your workflow."
            },
            {
                question: "What if an ingredient isn't in your database?",
                answer: "You can add custom ingredients with their nutritional profiles. We also regularly update our database with new ingredients. If you need help with custom ingredient analysis, our team can assist with finding appropriate nutritional data or recommend laboratory analysis when needed."
            },
            {
                question: "How do you handle recipe scaling and batch sizes?",
                answer: "Our platform automatically scales nutrition facts for any batch size or serving size. Whether you're making 10 units or 10,000 units, the nutrition facts per serving remain accurate. You can also compare nutrition facts across different batch formulations."
            },
            {
                question: "Is my recipe data secure and confidential?",
                answer: "Absolutely. We use enterprise-grade encryption, secure data centers, and strict access controls. Your recipe data is never shared with competitors or third parties. We also offer additional security features for Enterprise customers including single sign-on and custom data retention policies."
            }
        ],
        pricing: [
            {
                question: "Is there really a free trial?",
                answer: "Yes, all plans include a genuine 14-day free trial with full access to features. No credit card required to start. You can calculate nutrition facts, generate labels, and test all functionality during your trial period."
            },
            {
                question: "What happens when I exceed my product limit?",
                answer: "You'll receive notifications as you approach your plan limits. If you exceed your product limit, you can upgrade to a higher plan anytime with immediate effect. There are no overage fees - we'll simply prompt you to upgrade when needed."
            },
            {
                question: "Can I cancel my subscription anytime?",
                answer: "Yes, you can cancel your subscription at any time. If you cancel, you'll retain access to your account until the end of your current billing period. You can also export all your data before canceling. We offer a 30-day money-back guarantee for new subscriptions."
            },
            {
                question: "Do you offer discounts for nonprofits or educational institutions?",
                answer: "Yes, we offer special pricing for qualifying nonprofits, educational institutions, and startups. Contact our sales team with documentation of your organization status for discount eligibility and pricing details."
            },
            {
                question: "What's included in the Enterprise plan?",
                answer: "Enterprise includes unlimited products, dedicated account management, custom integrations, white-label options, advanced analytics, multi-facility management, and priority support. Pricing varies based on specific needs - contact sales for a custom quote."
            }
        ],
        account: [
            {
                question: "Can multiple team members access our account?",
                answer: "Yes, Professional plans include 5 user seats and Enterprise plans include unlimited users. You can set different permission levels for team members (view-only, editor, admin) and track who made changes to recipes. Additional users can be added to Professional plans for an extra fee."
            },
            {
                question: "How do you backup my data?",
                answer: "We perform automated daily backups with multiple redundancy layers. Your data is stored in secure, geographically distributed data centers. You can also export your own backups anytime in multiple formats. Enterprise customers can request custom backup schedules."
            },
            {
                question: "Can I import existing recipes from spreadsheets?",
                answer: "Yes, we provide recipe import tools for Excel and CSV files. Our team can also help migrate data from other nutrition software or legacy systems. There may be additional setup fees for complex data migrations on Enterprise plans."
            },
            {
                question: "What happens to my data if I cancel?",
                answer: "You retain access to export all your data for 30 days after cancellation. After that, your account is archived but not deleted for an additional 60 days. We permanently delete data only after 90 days total, giving you ample time to retrieve your information."
            },
            {
                question: "Do you provide training on how to use the platform?",
                answer: "Yes, we provide video tutorials, documentation, and webinar training for all users. Professional and Enterprise customers get personalized onboarding sessions. We also offer ongoing training for new team members and advanced features."
            }
        ]
    };

    const toggleQuestion = (questionIndex) => {
        setOpenQuestions(prev => ({
            ...prev,
            [questionIndex]: !prev[questionIndex]
        }));
    };

    const filteredQuestions = faqData[activeCategory].filter(faq =>
        faq.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
        faq.answer.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <section className="faq">
            <div className="faq-container">
                {/* Section Header */}
                <div className="section-header">
                    <div className="section-badge">
                        <span>Help Center</span>
                    </div>
                    <h2 className="section-title">
                        Frequently Asked
                        <span className="highlight"> Questions</span>
                    </h2>
                    <p className="section-description">
                        Find answers to common questions about nutrition labeling, compliance,
                        and our platform. Can't find what you're looking for? Contact our support team.
                    </p>
                </div>

                {/* Search Bar */}
                <div className="search-section">
                    <div className="search-box">
                        <div className="search-icon">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                <circle cx="11" cy="11" r="8" />
                                <path d="M21 21l-4.35-4.35" />
                            </svg>
                        </div>
                        <input
                            type="text"
                            placeholder="Search for answers..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="search-input"
                        />
                    </div>
                </div>

                {/* Category Navigation */}
                <div className="category-nav">
                    {categories.map((category) => (
                        <button
                            key={category.id}
                            className={`category-button ${activeCategory === category.id ? 'active' : ''}`}
                            onClick={() => setActiveCategory(category.id)}
                        >
                            <span className="category-icon">{category.icon}</span>
                            <span className="category-name">{category.name}</span>
                        </button>
                    ))}
                </div>

                {/* FAQ Content */}
                <div className="faq-content">
                    {filteredQuestions.length > 0 ? (
                        <div className="questions-list">
                            {filteredQuestions.map((faq, index) => (
                                <div key={index} className="question-item">
                                    <button
                                        className={`question-header ${openQuestions[index] ? 'open' : ''}`}
                                        onClick={() => toggleQuestion(index)}
                                    >
                                        <span className="question-text">{faq.question}</span>
                                        <span className="question-icon">
                                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                                <path d="M6 9l6 6 6-6" />
                                            </svg>
                                        </span>
                                    </button>

                                    <div className={`answer-content ${openQuestions[index] ? 'open' : ''}`}>
                                        <div className="answer-text">
                                            {faq.answer}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="no-results">
                            <div className="no-results-icon">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                    <circle cx="11" cy="11" r="8" />
                                    <path d="M21 21l-4.35-4.35" />
                                </svg>
                            </div>
                            <h3>No results found</h3>
                            <p>Try different keywords or browse categories above.</p>
                        </div>
                    )}
                </div>

                {/* Still Need Help Section */}
                <div className="help-section">
                    <div className="help-content">
                        <h3 className="help-title">Still Need Help?</h3>
                        <p className="help-description">
                            Our nutrition labeling experts are here to help with specific questions
                            about compliance, complex recipes, or technical implementation.
                        </p>
                        <div className="help-options">
                            <div className="help-option">
                                <div className="option-icon">
                                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
                                        <polyline points="22,6 12,13 2,6" />
                                    </svg>
                                </div>
                                <div className="option-content">
                                    <h4>Email Support</h4>
                                    <p>Get detailed answers to complex questions</p>
                                    <button className="option-button">Send Email</button>
                                </div>
                            </div>

                            <div className="help-option">
                                <div className="option-icon">
                                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                        <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
                                    </svg>
                                </div>
                                <div className="option-content">
                                    <h4>Schedule a Call</h4>
                                    <p>Talk directly with our nutrition experts</p>
                                    <button className="option-button">Book Call</button>
                                </div>
                            </div>

                            <div className="help-option">
                                <div className="option-icon">
                                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
                                    </svg>
                                </div>
                                <div className="option-content">
                                    <h4>Live Chat</h4>
                                    <p>Quick answers during business hours</p>
                                    <button className="option-button">Start Chat</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
};

export default FAQ;